### ISSUE TITLE
Reload Page No Cache

### ISSUE THREAD

**Issue by BenutzerEinsZweiDrei** [hibbitts-design/docsify-this#51]
So maybe im too stupid to do a hard reload on android 
But i tried with different browser and incognito tab 
And still the page stays the same

What worked for my docsify is this

`'cache-control': 'no-cache'`

From

https://github.com/docsifyjs/docsify/issues/602

**Comment by BenutzerEinsZweiDrei** [comment]
Also here

https://github.com/docsifyjs/docsify/issues/2118

**Comment by paulhibbitts** [comment]
Thanks for reporting the issue @BenutzerEinsZweiDrei. If you are needing to always clear the cache with using Docify-This you should be able to pass that standard Docsify config via a URL parm, for example:

https://docsify-this.net/?basePath=https://raw.githubusercontent.com/hibbitts-design/docsify-this-one-page-article/main&homepage=home.md&sidebar=true&cache-control=no-cache

Please let me know if this works on your Android config.

**Comment by BenutzerEinsZweiDrei** [comment]
As far as i understand this from this..

https://github.com/docsifyjs/docsify/blob/develop/docs/configuration.md#requestheaders

`cache-control` or all `requestheaders` (from the docsify config) 
are the headers sent by docsifyjs to get the files.

So i dont think i can change them from my side.

Maybe i could try deleting cookies for docsifyjs cdn url or somehow use javascript to make docsify rerun with new headers...

**Comment by paulhibbitts** [comment]
I should have originally asked where you stored the file, as with GitHub edits may be delayed to be available when accessing the raw Markdown which Docsify-This uses. You can see this yourself if you refresh the raw version (e.g. https://raw.githubusercontent.com/hibbitts-design/docsify-this-one-page-article/main/home.md for the GitHub file at https://github.com/hibbitts-design/docsify-this-one-page-article/blob/main/home.md) to confirm changes are actually available for Docsify-This to display etc.

Other than that I unfortunately don't have any other suggestions except to get your own instance of Docsify-This going and then make possible server-side changes there etc.

**Comment by paulhibbitts** [comment]
Closing this issue @BenutzerEinsZweiDrei but feel free to re-open if needed.
